name: spear-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - xarray
  - matplotlib
  - netcdf4
  - jupyter
  - python-dotenv
  - pydantic
  - pypdf
  - python-docx
  - pip
  - pip:
      - google-genai